const api=location.hostname.startsWith('app.')?`https://api.${location.hostname.slice(4)}`:'http://localhost:3000';
const $=s=>document.querySelector(s); let token=localStorage.ev2Token, language=localStorage.ev2Language||'es', activeEvent, activeFloor='planta_baja';
const copy={es:{night:'NIGHT CLUB · NOGALES, SONORA',title:'Tu noche, bajo control.',intro:'Reserva tu zona, pide bebidas y comparte un trago desde un solo lugar.',enter:'Entrar o registrarme',events:'Próximos eventos',orders:'Mi pedido',orderHint:'Escanea el QR de tu mesa o punto de entrega para solicitar bebidas.'},en:{night:'NIGHT CLUB · NOGALES, SONORA',title:'Your night, under control.',intro:'Reserve your area, order drinks and share a drink in one place.',enter:'Sign in or register',events:'Upcoming events',orders:'My order',orderHint:'Scan your table or delivery-point QR to order drinks.'}};
function translate(){document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=copy[language][e.dataset.i18n]);$('#language').textContent=language==='es'?'ES / EN':'EN / ES'}
async function request(path,options={}){const r=await fetch(api+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const body=await r.json();if(!r.ok)throw Error(body.error);return body}
const coords=(zone,index)=>{const c=zone.map_config||{};return {x:c.x??(12+(index%4)*23),y:c.y??(15+(Math.floor(index/4)%3)*27),w:c.w??18,h:c.h??18};};
async function renderMap(){if(!activeEvent)return;const zones=await request('/map/'+activeEvent.id), filtered=zones.filter(z=>z.floor===activeFloor);const map=$('#venueMap');map.dataset.floor=activeFloor;map.innerHTML=filtered.map((z,i)=>{const p=coords(z,i), reservable=z.reservable&&z.offer_id; const state=z.status==='reserved'?'reserved':reservable?'available':'unavailable';return `<button class="zone zone-${p.type||'table'} ${state}" style="left:${p.x}%;top:${p.y}%;width:${p.w}%;height:${p.h}%" data-zone="${z.id}" ${state!=='available'?'disabled':''}><span>${p.label||z.name}</span><small>${state==='available'?'Disponible':state==='reserved'?'Reservada':'No disponible'}</small></button>`}).join('')||'<p class="map-empty">Aún no se han cargado zonas para esta planta.</p>';document.querySelectorAll('.zone.available').forEach(b=>b.onclick=()=>selectZone(zones.find(z=>z.id===b.dataset.zone)));}
function money(value){return new Intl.NumberFormat(language==='es'?'es-MX':'en-US',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(value||0));}
function selectZone(zone){const extras=Number(zone.extra_ticket_enabled)?'Admite accesos extra según la configuración del evento.':'No admite accesos extra.';const included=Number(zone.included_credit_mxn)>0?`Incluye ${money(zone.included_credit_mxn)} de consumo.`:'El evento no incluye crédito de consumo.';$('#reservationSummary').innerHTML=`<p class="eyebrow">${zone.floor.replace('_',' ')}</p><h3>${zone.name}</h3><p class="price">${money(zone.offer_price_mxn)}</p><p>Incluye ${zone.included_tickets} accesos · capacidad base ${zone.capacity}${zone.extra_capacity?` + ${zone.extra_capacity} extras`:''}.</p><p>${included} ${extras}</p><p>Pago previo, QR individual de un solo uso e INE obligatoria al acceder.</p><button class="primary" id="startReservation">Pagar con Mercado Pago</button>`;$('#startReservation').onclick=()=>reserve(zone);}
async function reserve(zone){try{const defaultNames=Array.from({length:Number(zone.included_tickets)},(_,i)=>i===0?JSON.parse(atob(token.split('.')[1])).display_name:`Invitado ${i+1}`);const text=prompt(`Escribe los nombres de ${zone.included_tickets} invitados, separados por coma. Puedes agregar extras si esta zona lo permite.`,defaultNames.join(', '));if(text===null)return;const guests=text.split(',').map(x=>x.trim()).filter(Boolean);const created=await request('/reservations',{method:'POST',body:JSON.stringify({eventId:activeEvent.id,zoneId:zone.id,guests})});const payment=await request(`/payments/mercadopago/reservations/${created.reservation.id}`,{method:'POST',body:'{}'});location.assign(payment.checkoutUrl);}catch(error){alert(error.message)}}
async function openMap(event){activeEvent=event;$('#mapEventTitle').textContent=event.name;$('#reservationPanel').hidden=false;await renderMap();$('#reservationPanel').scrollIntoView({behavior:'smooth'});}
async function boot(){translate();if(!token)return;try{const events=await request('/events');$('#welcome').hidden=true;$('#session').hidden=false;const payload=JSON.parse(atob(token.split('.')[1]));$('#userName').textContent=`Hola, ${payload.display_name}`;$('#events').innerHTML=events.map(e=>`<article class="card"><b>${e.name}</b><p>${new Date(e.opens_at).toLocaleString()}</p><p>${e.exchange_rate?`USD/MXN: $${Math.floor(Number(e.exchange_rate))}`:'Tipo de cambio pendiente'}</p><button class="primary" data-event="${e.id}">Ver mapa y reservar</button></article>`).join('')||'<p>Aún no hay eventos publicados.</p>';document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>openMap(events.find(e=>e.id===b.dataset.event)));}catch{localStorage.removeItem('ev2Token');token=null}}
$('#language').onclick=()=>{language=language==='es'?'en':'es';localStorage.ev2Language=language;translate()};$('#showLogin').onclick=()=>$('#login').showModal();$('#showRegister').onclick=e=>{e.preventDefault();$('#login').close();$('#register').showModal()};$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await request('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});token=d.accessToken;localStorage.ev2Token=token;$('#login').close();boot()}catch(x){alert(x.message)}};$('#registerForm').onsubmit=async e=>{e.preventDefault();try{const d=await request('/auth/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});token=d.accessToken;localStorage.ev2Token=token;$('#register').close();boot()}catch(x){alert(x.message)}};$('#logout').onclick=()=>{localStorage.clear();location.reload()};document.querySelectorAll('.floor-tab').forEach(b=>b.onclick=async()=>{activeFloor=b.dataset.floor;document.querySelectorAll('.floor-tab').forEach(x=>x.classList.toggle('active',x===b));await renderMap();});$('#closeMap').onclick=()=>$('#reservationPanel').hidden=true;boot();
