import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import pg from 'pg';
import { token, hash, folio, audit, changeInventory, consumeRecipe, markOrderPaid, money } from './services.js';

const app = express(); const db = new pg.Pool({ connectionString: process.env.DATABASE_URL });
app.use(express.json()); app.use(cors({ origin: (process.env.CORS_ORIGINS || '').split(',').filter(Boolean) }));
const secret = process.env.JWT_SECRET || 'development-only-change-me';
const auth = (...roles) => (req,res,next) => { try { req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''), secret); if(roles.length && !roles.includes(req.user.role)) return res.status(403).json({error:'Sin permiso'}); next(); } catch { res.status(401).json({error:'Sesión requerida'}); } };
const asyncRoute = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next);

const paymentAmount = order => money(Number(order.subtotal) + Number(order.tip_mxn));
const mpConfigured = () => Boolean(process.env.MP_ACCESS_TOKEN && process.env.API_BASE_URL && process.env.APP_BASE_URL);
async function mercadoPagoPreference({ title, amount, externalReference }) {
  if (!mpConfigured()) throw new Error('Mercado Pago aún no está configurado por Administración');
  const response = await fetch('https://api.mercadopago.com/checkout/preferences', {
    method: 'POST', headers: { Authorization: `Bearer ${process.env.MP_ACCESS_TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ items: [{ title, quantity: 1, currency_id: 'MXN', unit_price: amount }], external_reference: externalReference,
      notification_url: `${process.env.API_BASE_URL}/webhooks/mercadopago`, back_urls: { success: `${process.env.APP_BASE_URL}/?payment=success`, failure: `${process.env.APP_BASE_URL}/?payment=failure`, pending: `${process.env.APP_BASE_URL}/?payment=pending` }, auto_return: 'approved' })
  });
  const data = await response.json();
  if (!response.ok) throw new Error(data.message || 'No fue posible iniciar Mercado Pago');
  return data;
}
async function confirmMercadoPago(paymentId) {
  if (!process.env.MP_ACCESS_TOKEN) throw new Error('Mercado Pago no está configurado');
  const response = await fetch(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(paymentId)}`, { headers: { Authorization: `Bearer ${process.env.MP_ACCESS_TOKEN}` } });
  const data = await response.json();
  if (!response.ok) throw new Error('No se pudo verificar el pago con Mercado Pago');
  return data;
}

app.get('/health', asyncRoute(async (_,res) => { await db.query('SELECT 1'); res.json({status:'ok'}); }));
app.post('/auth/register', asyncRoute(async (req,res) => { const {email,phone,password,displayName,dateOfBirth}=req.body; if(!password || !displayName || (!email && !phone)) return res.status(400).json({error:'Nombre, contraseña y correo o teléfono son requeridos'}); const result=await db.query('INSERT INTO users(email,phone,password_hash,display_name,date_of_birth) VALUES($1,$2,$3,$4,$5) RETURNING id,display_name,role',[email||null,phone||null,await bcrypt.hash(password,12),displayName,dateOfBirth||null]); const user=result.rows[0]; res.status(201).json({user,accessToken:jwt.sign(user,secret,{expiresIn:'12h'})}); }));
app.post('/auth/login', asyncRoute(async (req,res) => { const {identity,password}=req.body; const r=await db.query('SELECT * FROM users WHERE email=$1 OR phone=$1',[identity]); if(!r.rowCount || !await bcrypt.compare(password,r.rows[0].password_hash||'')) return res.status(401).json({error:'Credenciales inválidas'}); const u=r.rows[0]; res.json({user:{id:u.id,display_name:u.display_name,role:u.role},accessToken:jwt.sign({id:u.id,display_name:u.display_name,role:u.role},secret,{expiresIn:'12h'})}); }));
app.get('/events', asyncRoute(async (_,res)=> { const r=await db.query("SELECT * FROM events WHERE active=true AND closes_at > now() ORDER BY opens_at"); res.json(r.rows); }));
app.get('/products', asyncRoute(async (_,res)=> { const r=await db.query('SELECT * FROM products WHERE active=true ORDER BY category,name'); res.json(r.rows); }));
app.get('/pos/context', auth('waiter','cashier','manager','admin','bartender'), asyncRoute(async (_,res)=> {
  const [events,zones,bars]=await Promise.all([db.query("SELECT id,name,opens_at FROM events WHERE active AND closes_at>now() ORDER BY opens_at"),db.query('SELECT id,name,floor,bar_id FROM zones WHERE active ORDER BY floor,name'),db.query('SELECT id,name,floor FROM bars ORDER BY floor')]);
  res.json({events:events.rows,zones:zones.rows,bars:bars.rows});
}));
app.get('/orders/:id', auth(), asyncRoute(async(req,res)=> { const order=await db.query('SELECT o.*,z.name zone_name FROM orders o JOIN zones z ON z.id=o.zone_id WHERE o.id=$1',[req.params.id]);if(!order.rowCount)return res.status(404).json({error:'Pedido no encontrado'});const items=await db.query('SELECT oi.*,p.name FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=$1',[req.params.id]);res.json({...order.rows[0],items:items.rows}); }));
app.get('/bars', auth('bartender','waiter','manager','admin'), asyncRoute(async (_,res)=> { const r=await db.query('SELECT id,name,floor FROM bars ORDER BY floor'); res.json(r.rows); }));
app.get('/map/:eventId', asyncRoute(async (req,res)=> { const r=await db.query(`SELECT z.*,o.id offer_id,o.price_mxn offer_price_mxn,o.included_credit_mxn,o.included_products,o.included_tickets,o.extra_ticket_enabled,o.extra_ticket_price_mxn, CASE WHEN r.id IS NULL THEN 'available' ELSE 'reserved' END status FROM zones z LEFT JOIN event_zone_offers o ON o.zone_id=z.id AND o.event_id=$1 AND o.active LEFT JOIN reservations r ON r.zone_id=z.id AND r.event_id=$1 AND r.status IN ('paid','active') WHERE z.active ORDER BY z.floor,z.map_key`,[req.params.eventId]); res.json(r.rows); }));
app.post('/admin/events',auth('admin'),asyncRoute(async(req,res)=>{const {name,opensAt,closesAt,details='',exchangeRate}=req.body;if(!name||!opensAt||!closesAt)return res.status(400).json({error:'Nombre y horarios del evento son requeridos'});const c=await db.connect();try{await c.query('BEGIN');const event=await c.query('INSERT INTO events(name,opens_at,closes_at,details,exchange_rate,exchange_rate_date) VALUES($1,$2,$3,$4,$5,current_date) RETURNING *',[name,opensAt,closesAt,details,exchangeRate?Math.floor(Number(exchangeRate)):null]);await c.query("INSERT INTO event_zone_offers(event_id,zone_id,price_mxn,included_tickets,extra_ticket_enabled) SELECT $1,id,base_price_mxn,capacity,extra_capacity>0 FROM zones WHERE reservable AND active",[event.rows[0].id]);await audit(c,req.user.id,'event.created','event',event.rows[0].id);await c.query('COMMIT');res.status(201).json(event.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}));
app.post('/reservations', auth('customer','admin','reception'), asyncRoute(async (req,res)=>{
  const {eventId,zoneId,guests=[]}=req.body; if(!Array.isArray(guests)||guests.some(x=>typeof x!=='string'||!x.trim())) return res.status(400).json({error:'Indica los nombres de los invitados'});
  const c=await db.connect(); try { await c.query('BEGIN'); const offer=await c.query(`SELECT e.opens_at,o.price_mxn,o.included_credit_mxn,o.included_products,o.included_tickets,o.extra_ticket_enabled,o.extra_ticket_price_mxn,z.capacity,z.extra_capacity FROM event_zone_offers o JOIN events e ON e.id=o.event_id JOIN zones z ON z.id=o.zone_id WHERE o.event_id=$1 AND o.zone_id=$2 AND e.active AND o.active FOR UPDATE`,[eventId,zoneId]); if(!offer.rowCount) throw new Error('Zona no disponible para este evento'); const data=offer.rows[0], included=Number(data.included_tickets), extra=Math.max(0,guests.length-included);
  if(extra&&(!data.extra_ticket_enabled||extra>Number(data.extra_capacity))) throw new Error('La cantidad de accesos extra no está permitida'); const total=money(Number(data.price_mxn)+extra*Number(data.extra_ticket_price_mxn||0));
  const status=req.user.role==='customer'?'pending_payment':'paid'; const r=await c.query("INSERT INTO reservations(event_id,zone_id,owner_id,status,paid_mxn,included_credit_mxn,included_products,guest_manifest,hold_until) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[eventId,zoneId,req.user.id,status,total,data.included_credit_mxn,JSON.stringify(data.included_products),JSON.stringify(guests),new Date(new Date(data.opens_at).getTime()+3*3600e3)]);
  const tickets=[]; if(status==='paid') for(const name of guests){const raw=token();const t=await c.query('INSERT INTO tickets(reservation_id,holder_name,token_hash) VALUES($1,$2,$3) RETURNING id',[r.rows[0].id,name,hash(raw)]);tickets.push({id:t.rows[0].id,holderName:name,qrToken:raw});}
  await audit(c,req.user.id,`reservation.created_${status}`,'reservation',r.rows[0].id,{paidMxn:total}); await c.query('COMMIT'); res.status(201).json({reservation:r.rows[0],tickets});
  } catch(err){await c.query('ROLLBACK');throw err;}finally{c.release();}
}));
app.post('/payments/mercadopago/reservations/:id', auth('customer','admin','reception'), asyncRoute(async(req,res)=>{
  const r=await db.query('SELECT r.*,e.name event_name,z.name zone_name FROM reservations r JOIN events e ON e.id=r.event_id JOIN zones z ON z.id=r.zone_id WHERE r.id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Reserva no encontrada'});const reservation=r.rows[0];if(req.user.role==='customer'&&reservation.owner_id!==req.user.id)return res.status(403).json({error:'No puedes pagar esta reserva'});if(reservation.status!=='pending_payment')return res.status(409).json({error:'La reserva ya no requiere pago'});const preference=await mercadoPagoPreference({title:`EV2 · ${reservation.event_name} · ${reservation.zone_name}`,amount:Number(reservation.paid_mxn),externalReference:`reservation:${reservation.id}`});await db.query("INSERT INTO payment_transactions(reservation_id,provider,external_id,status,amount_mxn,checkout_url,raw_response) VALUES($1,'mercado_pago',$2,'pending',$3,$4,$5)",[reservation.id,preference.id,reservation.paid_mxn,preference.init_point||preference.sandbox_init_point,preference]);res.status(201).json({provider:'mercado_pago',checkoutUrl:preference.init_point||preference.sandbox_init_point});
}));
app.post('/access/scan', auth('security','reception','manager','admin'), asyncRoute(async (req,res)=>{ const {qrToken,approvedAge,reason}=req.body; const r=await db.query('SELECT t.*,rsv.id reservation_id FROM tickets t JOIN reservations rsv ON rsv.id=t.reservation_id WHERE t.token_hash=$1 FOR UPDATE',[hash(qrToken)]); if(!r.rowCount) return res.status(404).json({error:'Código no válido'}); const t=r.rows[0]; if(t.status!=='issued') return res.status(409).json({error:`Acceso ${t.status}`}); const status=approvedAge?'entered':'denied'; await db.query('UPDATE tickets SET status=$1,entered_at=CASE WHEN $1=\'entered\' THEN now() END,denial_reason=$2 WHERE id=$3',[status,reason||null,t.id]); if(approvedAge) await db.query("UPDATE reservations SET status='active', activated_at=COALESCE(activated_at,now()) WHERE id=$1",[t.reservation_id]); await audit(db,req.user.id,`ticket.${status}`,'ticket',t.id,{reason}); res.json({status,holderName:t.holder_name}); }));
app.post('/access/contingency', auth('reception','manager','admin'), asyncRoute(async(req,res)=>{const {ticketId,reason}=req.body;if(!ticketId||!reason)return res.status(400).json({error:'Acceso y motivo son requeridos'});const t=await db.query('SELECT id,status FROM tickets WHERE id=$1 FOR UPDATE',[ticketId]);if(!t.rowCount||t.rows[0].status!=='issued')return res.status(409).json({error:'Ese acceso ya no puede generar contingencia'});const raw=token();const p=await db.query("INSERT INTO contingency_passes(ticket_id,issued_by,token_hash,reason,expires_at) VALUES($1,$2,$3,$4,now()+interval '15 minutes') RETURNING id,expires_at",[ticketId,req.user.id,hash(raw),reason]);await audit(db,req.user.id,'ticket.contingency_issued','ticket',ticketId,{reason,expiresAt:p.rows[0].expires_at});res.status(201).json({passId:p.rows[0].id,qrToken:raw,expiresAt:p.rows[0].expires_at});}));
app.post('/tickets/:id/reassign',auth('customer','admin','reception'),asyncRoute(async(req,res)=>{const {holderName,holderPhone}=req.body;if(!holderName)return res.status(400).json({error:'El nombre del nuevo invitado es requerido'});const c=await db.connect();try{await c.query('BEGIN');const old=await c.query('SELECT t.*,r.owner_id FROM tickets t JOIN reservations r ON r.id=t.reservation_id WHERE t.id=$1 FOR UPDATE',[req.params.id]);if(!old.rowCount)throw new Error('Acceso no encontrado');if(req.user.role==='customer'&&old.rows[0].owner_id!==req.user.id)throw new Error('Solo el titular puede reasignar este acceso');if(!['issued','denied'].includes(old.rows[0].status))throw new Error('Un acceso ya utilizado no puede reasignarse');await c.query("UPDATE tickets SET status='revoked' WHERE id=$1",[old.rows[0].id]);const raw=token();const created=await c.query('INSERT INTO tickets(reservation_id,holder_name,holder_phone,token_hash,reassigned_from) VALUES($1,$2,$3,$4,$5) RETURNING id',[old.rows[0].reservation_id,holderName,holderPhone||null,hash(raw),old.rows[0].id]);await audit(c,req.user.id,'ticket.reassigned','ticket',created.rows[0].id,{reassignedFrom:old.rows[0].id});await c.query('COMMIT');res.status(201).json({id:created.rows[0].id,holderName,qrToken:raw});}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}));
app.post('/orders', auth('customer','waiter','admin'), asyncRoute(async (req,res)=>{const {eventId,zoneId,items,currency='MXN',tipMxn=0,waiterId}=req.body; if(!items?.length) return res.status(400).json({error:'El pedido no contiene productos'}); const c=await db.connect(); try {await c.query('BEGIN'); const z=await c.query('SELECT bar_id FROM zones WHERE id=$1',[zoneId]); if(!z.rowCount) throw new Error('Zona inválida'); const ids=items.map(i=>i.productId); const products=await c.query('SELECT id,price_mxn FROM products WHERE id=ANY($1::uuid[]) AND active=true',[ids]); if(products.rowCount!==ids.length) throw new Error('Producto no disponible'); const prices=new Map(products.rows.map(p=>[p.id,Number(p.price_mxn)])); const subtotal=items.reduce((s,i)=>s+prices.get(i.productId)*i.quantity,0); const order=await c.query('INSERT INTO orders(folio,event_id,zone_id,bar_id,customer_id,waiter_id,currency,subtotal,tip_mxn) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[folio(),eventId,zoneId,z.rows[0].bar_id,req.user.id,waiterId||null,currency,subtotal,tipMxn]); for(const i of items) await c.query('INSERT INTO order_items(order_id,product_id,quantity,unit_price_mxn,notes) VALUES($1,$2,$3,$4,$5)',[order.rows[0].id,i.productId,i.quantity,prices.get(i.productId),i.notes||null]); await audit(c,req.user.id,'order.created','order',order.rows[0].id); await c.query('COMMIT'); res.status(201).json(order.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}));
app.post('/orders/:id/pay', auth('waiter','cashier','admin'), asyncRoute(async(req,res)=>{
  const {method,reference=''}=req.body;
  if(!['cash','terminal'].includes(method)) return res.status(400).json({error:'Use Mercado Pago para cobro web; aquí solo se libera efectivo o terminal'});
  if(method==='terminal'&&!reference.trim()) return res.status(400).json({error:'Registra la autorización o referencia de la terminal'});
  const c=await db.connect();try{await c.query('BEGIN');const paid=await markOrderPaid(c,req.params.id,{method,actorId:req.user.id,externalId:reference||null});await c.query('INSERT INTO payment_transactions(order_id,provider,external_id,status,amount_mxn,paid_at) VALUES($1,$2,$3,\'approved\',$4,now())',[paid.id,method,reference||null,paymentAmount(paid)]);await c.query('COMMIT');res.json(paid);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}
}));
app.post('/payments/mercadopago/orders/:id', auth('customer','waiter','admin'), asyncRoute(async(req,res)=>{
  const order=await db.query('SELECT * FROM orders WHERE id=$1',[req.params.id]);
  if(!order.rowCount) return res.status(404).json({error:'Pedido no encontrado'});
  const value=order.rows[0];
  if(req.user.role==='customer'&&value.customer_id!==req.user.id) return res.status(403).json({error:'No puedes pagar este pedido'});
  if(value.status!=='pending_payment') return res.status(409).json({error:'El pedido ya no requiere pago'});
  const preference=await mercadoPagoPreference({title:`EV2 · Pedido ${value.folio}`,amount:paymentAmount(value),externalReference:`order:${value.id}`});
  await db.query("INSERT INTO payment_transactions(order_id,provider,external_id,status,amount_mxn,checkout_url,raw_response) VALUES($1,'mercado_pago',$2,'pending',$3,$4,$5)",[value.id,preference.id,paymentAmount(value),preference.init_point||preference.sandbox_init_point,preference]);
  res.status(201).json({provider:'mercado_pago',checkoutUrl:preference.init_point||preference.sandbox_init_point,preferenceId:preference.id});
}));
app.post('/webhooks/mercadopago', asyncRoute(async(req,res)=>{
  const paymentId=req.body?.data?.id||req.query['data.id']||req.body?.id;
  if(!paymentId) return res.status(202).json({received:true});
  const payment=await confirmMercadoPago(paymentId);
  if(payment.status!=='approved') return res.status(202).json({received:true});
  const reference=String(payment.external_reference||''), c=await db.connect();
  try{await c.query('BEGIN');
    if(reference.startsWith('order:')) { const orderId=reference.slice(6), order=await c.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[orderId]);if(!order.rowCount)throw new Error('Pedido de pago no encontrado');if(money(payment.transaction_amount)!==paymentAmount(order.rows[0]))throw new Error('Importe de pago no coincide');await c.query("UPDATE payment_transactions SET external_id=$1,status='approved',raw_response=$2,paid_at=now() WHERE order_id=$3 AND provider='mercado_pago'",[String(payment.id),payment,orderId]);await markOrderPaid(c,orderId,{method:'mercado_pago',actorId:null,externalId:String(payment.id)}); }
    else if(reference.startsWith('reservation:')) { const reservationId=reference.slice(12), r=await c.query('SELECT * FROM reservations WHERE id=$1 FOR UPDATE',[reservationId]);if(!r.rowCount)throw new Error('Reserva de pago no encontrada');const reservation=r.rows[0];if(money(payment.transaction_amount)!==money(reservation.paid_mxn))throw new Error('Importe de reserva no coincide');if(reservation.status==='pending_payment'){await c.query("UPDATE reservations SET status='paid' WHERE id=$1",[reservationId]);for(const name of reservation.guest_manifest){const raw=token();await c.query('INSERT INTO tickets(reservation_id,holder_name,token_hash) VALUES($1,$2,$3)',[reservationId,name,hash(raw)]);}await audit(c,null,'reservation.paid','reservation',reservationId,{externalId:String(payment.id)});}await c.query("UPDATE payment_transactions SET external_id=$1,status='approved',raw_response=$2,paid_at=now() WHERE reservation_id=$3 AND provider='mercado_pago'",[String(payment.id),payment,reservationId]); }
    else throw new Error('Referencia de pago desconocida');
    await c.query('COMMIT');res.json({received:true});
  }catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}
}));
app.get('/bar/orders', auth('bartender','manager','admin'), asyncRoute(async(req,res)=> { const r=await db.query("SELECT o.*,z.name zone_name FROM orders o JOIN zones z ON z.id=o.zone_id WHERE o.bar_id=$1 AND o.status='paid' ORDER BY o.paid_at",[req.query.barId]); res.json(r.rows); }));
app.post('/orders/:id/ready', auth('bartender','manager','admin'), asyncRoute(async(req,res)=>{const r=await db.query("UPDATE orders SET status='ready',ready_at=now() WHERE id=$1 AND status IN ('paid','in_preparation') RETURNING *",[req.params.id]);if(!r.rowCount)return res.status(409).json({error:'Pedido no disponible'});await audit(db,req.user.id,'order.ready','order',r.rows[0].id);res.json(r.rows[0]);}));
app.get('/waiter/orders',auth('waiter','manager','admin'),asyncRoute(async(req,res)=> { const r=await db.query("SELECT o.*,z.name zone_name FROM orders o JOIN zones z ON z.id=o.zone_id WHERE o.status='ready' AND (o.waiter_id=$1 OR $2::boolean) ORDER BY o.ready_at",[req.user.id,['manager','admin'].includes(req.user.role)]); res.json(r.rows); }));
app.get('/waiter/pending',auth('waiter','cashier','manager','admin'),asyncRoute(async(req,res)=> { const r=await db.query("SELECT o.*,z.name zone_name FROM orders o JOIN zones z ON z.id=o.zone_id WHERE o.status='pending_payment' AND (o.waiter_id=$1 OR $2::boolean) ORDER BY o.created_at DESC",[req.user.id,['cashier','manager','admin'].includes(req.user.role)]); res.json(r.rows); }));
app.post('/orders/:id/deliver',auth('waiter','manager','admin'),asyncRoute(async(req,res)=>{const r=await db.query("UPDATE orders SET status='delivered',delivered_at=now() WHERE id=$1 AND status='ready' RETURNING *",[req.params.id]);if(!r.rowCount)return res.status(409).json({error:'Pedido no listo'});await audit(db,req.user.id,'order.delivered','order',r.rows[0].id);res.json(r.rows[0]);}));
app.post('/inventory/movements',auth('warehouse','manager','admin'),asyncRoute(async(req,res)=>{await changeInventory(db,{...req.body,actorId:req.user.id});await audit(db,req.user.id,'inventory.moved','inventory',req.body.productId,req.body);res.status(201).json({ok:true});}));
app.get('/flirty/visible',auth(),asyncRoute(async(_,res)=> { const r=await db.query("SELECT id,display_name,photo_url FROM users WHERE flirty_visible=true AND role='customer'"); res.json(r.rows); }));
app.post('/flirty',auth('customer'),asyncRoute(async(req,res)=>{const {orderId,recipientId,visibility='named'}=req.body;const order=await db.query("SELECT id FROM orders WHERE id=$1 AND customer_id=$2 AND status='paid'",[orderId,req.user.id]);if(!order.rowCount)return res.status(400).json({error:'El regalo debe estar pagado antes de enviarse'});const recipient=await db.query("SELECT id FROM users WHERE id=$1 AND flirty_visible=true AND role='customer'",[recipientId]);if(!recipient.rowCount)return res.status(400).json({error:'La persona no está disponible en Flirty'});const r=await db.query('INSERT INTO flirty_gifts(order_id,sender_id,recipient_id,visibility) VALUES($1,$2,$3,$4) RETURNING *',[orderId,req.user.id,recipientId,visibility]);await audit(db,req.user.id,'flirty.sent','flirty_gift',r.rows[0].id);res.status(201).json(r.rows[0]);}));
app.post('/flirty/:orderId/respond',auth('customer'),asyncRoute(async(req,res)=>{const status=req.body.accept?'accepted':'rejected';const r=await db.query("UPDATE flirty_gifts SET status=$1,responded_at=now() WHERE order_id=$2 AND recipient_id=$3 AND status='pending' RETURNING *",[status,req.params.orderId,req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Regalo no disponible'});res.json(r.rows[0]);}));
app.get('/admin/payment-providers',auth('admin'),asyncRoute(async(_,res)=> { const r=await db.query('SELECT id,name,enabled,updated_at FROM payment_providers ORDER BY name'); res.json(r.rows); }));
app.put('/admin/payment-providers/:id',auth('admin'),asyncRoute(async(req,res)=>{const {enabled,configuration={}}=req.body;const r=await db.query('UPDATE payment_providers SET enabled=$1,configuration=$2,updated_at=now() WHERE id=$3 RETURNING id,name,enabled,updated_at',[enabled,configuration,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Proveedor no encontrado'});await audit(db,req.user.id,'payment_provider.updated','payment_provider',req.params.id,{enabled});res.json(r.rows[0]);}));
app.put('/admin/events/:id/exchange-rate',auth('admin'),asyncRoute(async(req,res)=>{const rate=Math.floor(Number(req.body.bankRate));if(!Number.isFinite(rate)||rate<=0)return res.status(400).json({error:'Tipo de cambio inválido'});const r=await db.query('UPDATE events SET exchange_rate=$1,exchange_rate_date=current_date WHERE id=$2 RETURNING *',[rate,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Evento no encontrado'});await audit(db,req.user.id,'exchange_rate.updated','event',req.params.id,{bankRate:req.body.bankRate,rate});res.json(r.rows[0]);}));
app.use((err,_,res,__)=>{console.error(err);res.status(err.code==='23505'?409:400).json({error:err.message||'Error inesperado'});});
app.listen(process.env.PORT||3000,()=>console.log('EV2 API running'));
