const api=location.hostname.startsWith('pos.')?`https://api.${location.hostname.slice(4)}`:'http://localhost:3000';
const $=s=>document.querySelector(s);let token=localStorage.ev2PosToken, context, products=[], cart=[];
const headers=()=>({'Content-Type':'application/json',Authorization:`Bearer ${token}`});
async function call(path,opt={}){const r=await fetch(api+path,{...opt,headers:headers()});const b=await r.json();if(!r.ok)throw Error(b.error);return b}
function show(name){document.querySelectorAll('main section').forEach(x=>x.hidden=x.id!==name);$('#title').textContent={orders:'Pedidos',bar:'Barra',entry:'Acceso',inventory:'Inventario'}[name];if(name==='bar')loadBar();if(name==='orders')loadOrders()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
function mxn(value){return new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(value||0))}
async function setup(){[context,products]=await Promise.all([call('/pos/context'),call('/products')]);$('#event').innerHTML='<option value="">Evento</option>'+context.events.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');$('#zone').innerHTML='<option value="">Mesa / zona</option>'+context.zones.map(x=>`<option value="${x.id}">${x.floor.replace('_',' ')} · ${x.name}</option>`).join('');$('#product').innerHTML='<option value="">Producto</option>'+products.map(x=>`<option value="${x.id}">${x.name} · ${mxn(x.price_mxn)}</option>`).join('');$('#barSelector').innerHTML=context.bars.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');}
function renderCart(){const total=cart.reduce((n,x)=>n+x.quantity*Number(x.price_mxn),0)+Number($('#tip').value||0);$('#cart').innerHTML=cart.map((x,i)=>`<div class="line"><span>${x.name} × ${x.quantity}</span><b>${mxn(x.quantity*x.price_mxn)}</b><button onclick="removeItem(${i})">×</button></div>`).join('')+(cart.length?`<p><b>Total: ${mxn(total)}</b></p>`:'Sin productos');$('#createOrder').disabled=!cart.length;}
window.removeItem=i=>{cart.splice(i,1);renderCart()};
$('#newOrderForm').onsubmit=e=>{e.preventDefault();const product=products.find(x=>x.id===$('#product').value),quantity=Number($('#quantity').value);if(!product||!quantity)return;const existing=cart.find(x=>x.id===product.id);if(existing)existing.quantity+=quantity;else cart.push({...product,quantity});renderCart()};$('#tip').oninput=renderCart;
$('#createOrder').onclick=async()=>{try{const payload={eventId:$('#event').value,zoneId:$('#zone').value,items:cart.map(x=>({productId:x.id,quantity:x.quantity})),tipMxn:Number($('#tip').value||0)};if(!payload.eventId||!payload.zoneId)throw Error('Selecciona evento y zona');const order=await call('/orders',{method:'POST',body:JSON.stringify(payload)});cart=[];renderCart();const method=prompt('Método de cobro: efectivo o terminal','efectivo');if(method==='efectivo'||method==='cash')await pay(order.id,'cash');else if(method==='terminal'){const reference=prompt('Autorización de la terminal');if(reference)await pay(order.id,'terminal',reference)}else alert(`Pedido ${order.folio} creado; falta cobrarlo.`);loadOrders()}catch(error){alert(error.message)}};
async function pay(id,method,reference=''){try{await call(`/orders/${id}/pay`,{method:'POST',body:JSON.stringify({method,reference})});alert('Pago confirmado. El pedido ya fue enviado a barra.')}catch(error){alert(error.message)}}
async function loadOrders(){try{const [ready,pending]=await Promise.all([call('/waiter/orders'),call('/waiter/pending')]);$('#orderList').innerHTML=ready.map(o=>`<article class="order"><span><b>${o.folio}</b><br>${o.zone_name}</span><span>Listo ${new Date(o.ready_at).toLocaleTimeString()}</span><button onclick="deliver('${o.id}')">Entregado</button></article>`).join('')||'No hay pedidos listos.';$('#pendingList').innerHTML=pending.map(o=>`<article class="order"><span><b>${o.folio}</b><br>${o.zone_name} · ${mxn(Number(o.subtotal)+Number(o.tip_mxn))}</span><span><button onclick="pay('${o.id}','cash')">Efectivo</button> <button onclick="terminal('${o.id}')">Terminal</button></span></article>`).join('')||'No hay pedidos pendientes de pago.'}catch(x){$('#orderList').textContent=x.message}}
async function loadBar(){try{const id=$('#barSelector').value;if(!id)return;const data=await call('/bar/orders?barId='+encodeURIComponent(id));$('#barList').innerHTML=data.map(o=>`<article class="order"><span><b>${o.folio}</b><br>${o.zone_name}</span><span>Pagado ${new Date(o.paid_at).toLocaleTimeString()}</span><button onclick="ready('${o.id}')">Listo</button></article>`).join('')||'No hay pedidos pagados.'}catch(x){$('#barList').textContent=x.message}}
$('#barSelector').onchange=loadBar;window.deliver=async id=>{await call('/orders/'+id+'/deliver',{method:'POST'});loadOrders()};window.ready=async id=>{await call('/orders/'+id+'/ready',{method:'POST'});loadBar()};window.pay=pay;window.terminal=id=>{const reference=prompt('Autorización de la terminal');if(reference)pay(id,'terminal',reference)};
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await fetch(api+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}),d=await r.json();if(!r.ok)throw Error(d.error);token=d.accessToken;localStorage.ev2PosToken=token;$('#login').hidden=true;$('#identity').textContent=`${d.user.display_name} · ${d.user.role}`;await setup();show(d.user.role==='bartender'?'bar':'orders')}catch(x){alert(x.message)}};
$('#scanForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.approvedAge=!!e.target.approvedAge.checked;try{const r=await call('/access/scan',{method:'POST',body:JSON.stringify(f)});$('#scanResult').textContent=`${r.holderName}: ${r.status==='entered'?'acceso autorizado':'acceso denegado'}`}catch(x){$('#scanResult').textContent=x.message}};
if(token){$('#login').hidden=true;setup().then(()=>show('orders')).catch(()=>{localStorage.removeItem('ev2PosToken');location.reload()})}
